### ISSUE TITLE
Improve Permissions

### ISSUE THREAD

**Issue by purplespider** [heyday/silverstripe-menumanager#12]
I don't think the default permissions are quite right here.

Currently CMS users can be given 2 permissions:
1. Create/Edit/Delete/View **Menu Sets**
2. Create/Edit/Delete/View **Menu Items**

However, I don't see the point in normal CMS users being able to create or delete a Menu Set, as this is something that the developer sets up in the templates.

It should be possible to restrict CMS users to only be able to **view** Menu **Sets**, and create/edit/delete Menu **Items**.

**Comment by camspiers** [comment]
Happy to accept a PR if you are keen to do the work. I think that what you are saying makes sense.
