### ISSUE TITLE
Working with subsites

### ISSUE THREAD

**Issue by mediabeastnz** [heyday/silverstripe-menumanager#25]
I haven't looked thoroughly through the code of this module yet so sorry if these are silly assumptions/questions.

What would be required to make this module work with the Subsite module?

From a quick glance i can set we'd need to set a relation on the menuset to have one subsite id.
We'd also need to make sure the model admin only displays menu sets and items for that particular subsite.

Is there anything else that would need to be added? e.g. permissions etc?

**Comment by mediabeastnz** [comment]
Oh and there would need to be a change to how the template retrieves the right menuset

**Comment by mi32dogs** [comment]
there is a version that works with subsites guttmann / silverstripe-menumanager-subsites
