### ISSUE TITLE
SilverStripe 4 support

### ISSUE THREAD

**Issue by nikrolls** [heyday/silverstripe-menumanager#26]
Any plans on SilverStripe 4 support? It's going into beta soon and I'm keen to work on migrating our sites as early as possible.

**Comment by pitchandtone** [comment]
^

**Comment by camspiers** [comment]
I'll take a look this weekend (US Time)

**Comment by bendubuisson** [comment]
checkout https://github.com/heyday/silverstripe-menumanager/releases/tag/3.0.0
