### ISSUE TITLE
silverstripe-vendormodule not released

### ISSUE THREAD

**Issue by alexoconner** [heyday/silverstripe-menumanager#36]
Hello,

it looks like the silverstripe 4 version (3.x) isn't released as type "silverstripe-vendormodule" but "silverstripe-module" instead. If I install this from master its correct using "silverstripe-vendormodule" but not if I install 3.x
It would be good if that could get released so that the module will be installed inside the vendor folder.

thanks!

**Comment by eehondas** [comment]
+1 to @alexoconner

**Comment by christopherdarling** [comment]
Can be closed - released in 3.0.4+

**Comment by HJGreen** [comment]
Thanks for reporting, fixed in #31
