### ISSUE TITLE
UX: 'Link Existing' steals link

### ISSUE THREAD

**Issue by jonom** [heyday/silverstripe-menumanager#41]
This is probably an issue with GridField rather than this module but was trying this module for the first time and needed to use the same link in more than one menu. I saw the 'Find Existing' button and thought 'Beauty, must be a many-many', and I added the existing link. Realised afterwards that it actually 'stole' the link from my other menu.

Feel free to close but I figured if this can trip up a Silverstripe developer it could easily trip up a CMS user.

**Comment by wilr** [comment]
I've removed the default autocompleter from the config. As you found it's likely to catch people out with complex menus and easier for people to simply re-add per menu. Fixed in 4.1
