### ISSUE TITLE
Can't delete duplicates of default sets

### ISSUE THREAD

**Issue by jakxnz** [heyday/silverstripe-menumanager#42]
When a default menu set is created twice, the duplicate cannot be deleted from the CMS

## Versions

```
silverstripe/framework                                   4.5.2
heyday/silverstripe-menumanager                          dev-master 366c211
```

## Steps to reproduce

1. Configure a set name in `default_sets`
2. Run `dev/build`
3. Create another set with the same `Name` (e.g via the CMS or with `dnadesign/silverstripe-populate`)
5. On the Menu Management section in the CMS
6. Attempt to delete the duplicate Menu Set

## Expected

I can delete the second, duplicate Menu Set

## Actual

I cannot delete the second, duplicate Menu Set

**Comment by HJGreen** [comment]
Resolved in release [`3.2.0`](https://github.com/heyday/silverstripe-menumanager/releases/tag/3.2.0)
