### ISSUE TITLE
TRANSLATABLE translations menu logic

### ISSUE THREAD

**Issue by promotion** [heyday/silverstripe-menumanager#46]
Hi, 
I'm trying to integrate your module to the SS 3.7 site which has TRANSLATABLE installed. As I need different menus for different languages (As lot sof languges have its own pages tree), i thought i could have create different menu sets, and use them for each language. 

However whatever i do - when i try to crate a menu - the Tree Dropdown with pages list would show English pages only, so in fact i never see other languges Tree, and cannot pick a page from that language. 

Can you advice, what would be fastest way of making different langue menusets possible ?

Thanks
PS - i also installed silverstripe-menumanager-squared , not sure if this would have any impact on solution ?

**Comment by wilr** [comment]
Closing as Transable module is no longer supported - [Fluent](https://github.com/tractorcow-farm/silverstripe-fluent) is a better option and as I understand this should integrate with Menu Manager
