### ISSUE TITLE
Nested Menu

### ISSUE THREAD

**Issue by gazi786** [heyday/silverstripe-menumanager#50]
Is there a any feature in this add-on to cater for nested menu..?

**Comment by HJGreen** [comment]
Hi @gazi786 

There is currently no way to build nested menus within the CMS. However, for the simplest use-case you can loop through the children of any menu item:

```html
<ul>
<% loop $MenuItems %>
    <li>
        <a class="menu-item-level-1" href="$Link.ATT">$MenuTitle.XML</a>
        <% if $Children %>
            <ul>
            <% loop $Children %>
                <li>
                    <a class="menu-item-level-2" href="$Link.ATT">$MenuTitle.XML</a>
                </li>
            <% end_loop %>
            </ul>
        <% end_if %>
    </li>
<% end_loop %>
</ul>
```

If that doesn't fill your requirements, I would recommend taking a look at the following modules:
- https://github.com/gorriecoe/silverstripe-menu
- https://github.com/Marketo/SilverStripe-MenuManager-Squared

**Comment by gazi786** [comment]
Thanks, mate.

**Comment by andreaslindahl** [comment]
I can't get this to work in Silverstripe 6. Works fine in version 5, but after upgrading the Children array seems to be empty
