### ISSUE TITLE
Call canCreate on extensions for MenuItem and MenuSet

### ISSUE THREAD

**Issue by scott1702** [heyday/silverstripe-menumanager#56]
For both MenuSet and MenuItem, they should call canCreate on any applied extensions to make it easier to disable the ability to create those items

**Comment by wilr** [comment]
@scott1702 doesn't the extension get called via `DataObject::extendedCan`? As far as I know we don't need to manually call extended can within our class (unless someone had `MANAGE_MENU_SETS` and you wanted to disable it).

From MenuSet:
```
    public function canCreate($member = null, $context = [])
    {
        if (Permission::check('MANAGE_MENU_SETS')) {
            return true;
        }

        return parent::canCreate($member, $context);
    }
```

**Comment by wilr** [comment]
Fixed in 3 and 4
