### ISSUE TITLE
Please create new release with latest chnages

### ISSUE THREAD

**Issue by andreaspiening** [heyday/silverstripe-menumanager#60]
Hi mate,

could you help me by releasing your change from 347cc65?

```
SilverStripe\Subsites\Model\Subsite:
  has_many:
    - MenuSets => 'Heyday\MenuManager\MenuSet'
```
That double arrow in 4.1.1 is giving me headaches :)

Cheers

Andy

**Comment by wilr** [comment]
https://github.com/heyday/silverstripe-menumanager/releases/tag/4.1.2
