### ISSUE TITLE
Add default 'menu sets' via config

### ISSUE THREAD

**Issue by chasevida** [heyday/silverstripe-menumanager#8]
Thanks for the module, works great. I just have a feature request.

I'm wondering if you can add default menu sets programatically via a config file or something? Obviously no links but just a few menus that can't be deleted so someone can populate them.

**Comment by stecman** [comment]
Nice idea @chasevida. This would be reasonably straight forward to implement using `DataObject::requireDefaultRecords()` - we'd definitely accept a pull request for this.

**Comment by chasevida** [comment]
Ok, if I get a chance I'll see what I can whip up.
